name: Tam Donanimli APK Yapici
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Java Kurulumu
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Flutter Kurulumu
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Flet ve Paketleme
        run: |
          pip install flet
          flet build apk

      - name: APK Dosyasini Teslim Et
        uses: actions/upload-artifact@v4
        with:
          name: YKS_Net_OBP_Robotu
          path: build/apk/app-release.apk
